// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsX.Data;

namespace SportsX.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220201140345_Fourth")]
    partial class Fourth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SportsX.Entities.Telefone", b =>
                {
                    b.Property<int>("ID_TELEFONE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("NR_TELEFONE")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_TELEFONE");

                    b.ToTable("TELEFONE");
                });

            modelBuilder.Entity("SportsX.Entity.Endereco", b =>
                {
                    b.Property<int>("ID_ENDERECO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ID")
                        .HasColumnType("INT");

                    b.Property<string>("NR_CEP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_ENDERECO");

                    b.ToTable("ENDERECO");
                });

            modelBuilder.Entity("SportsX.Entity.PFisica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DS_CLASSIFICACAO")
                        .HasColumnType("BIT");

                    b.Property<string>("DS_EMAIL")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("DS_NOME")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NR_CPF")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("ID");

                    b.ToTable("PFISICA");
                });

            modelBuilder.Entity("SportsX.Entity.PJuridica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DS_CLASSIFICACAO")
                        .HasColumnType("BIT");

                    b.Property<string>("DS_EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DS_RAZAO_SOCIAL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NR_CNPJ")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ID");

                    b.ToTable("PJURIDICA");
                });
#pragma warning restore 612, 618
        }
    }
}
